Feature/v1.0.1
GalaxeTV/Genesis pull request #28
Opened 2024-01-08 16:19 UTC by josefbaltz

### Information

This PR fixes #27 and a couple other critical bugs found during development.

### Details

* Added a way for users to set their class to default via /greset or /genesisreset  
* Made the GUIs for each class static so multiple users can use the menu at the same time.  
* Resolved an issue with GSit and the permanent swiftsneak ability where a player could have a boosted movement speed without having to sneak.  
* Resolved an issue where players who had their class reset manually would have the same amount of hearts.  
* Fully implemented the class selection GUI to give descriptions of class abilities.  
* Re-balance the default configuration file shipped with the plugin.
* Removed redundant and unused config file entries.

### *Requesting that this be pushed to production as soon as testing is complete as this branch fixes critical bugs and user experience issues with the plugin*

2024-01-08 16:32 UTC, garrettsummerfi3ld requested changes
Only one required change from my part. Will test more when I have time to sit down with the builds.

2024-01-08 16:32 UTC, garrettsummerfi3ld commented on build.gradle
> +version = '1.0.1'
We should probably look into Git tagging in the future for builds like these.

2024-01-08 16:32 UTC, garrettsummerfi3ld commented on src/main/java/tv/galaxe/genesis/cmd/ResetClass.java
> +		return true;
Only required change from me for this is we should probably be behind a check that the player NEEDS to confirm, didn't we want to have a cooldown for selecting classes (1 day, etc.)?

In the future there could also be an argument for staff to easily reset other players as well, but its not required at the moment.

2024-01-08 16:32 UTC, garrettsummerfi3ld commented on src/main/resources/plugin.yml
> +    aliases: [genreset, greset]
Need to test this personally, but do we want to have `/genesis` throw a message to the player if they cannot switch classes right now to run this command? Would help preventing confusion.

2024-01-08 18:27 UTC, josefbaltz commented on build.gradle
> +version = '1.0.1'
Absolutely agree

2024-01-08 18:29 UTC, josefbaltz commented on src/main/java/tv/galaxe/genesis/cmd/ResetClass.java
> +		return true;
For now I'm okay with not requiring a confirmation. In a future update I intend to implement time stamp checking to validate that users have waited a week (or whatever is specified by the configuration file) before switching classes. Since there's no cool down there's really not an issue with it. If you'd still like me to implement a confirmation I can do that.

2024-01-08 18:30 UTC, josefbaltz commented on src/main/resources/plugin.yml
> +    aliases: [genreset, greset]
Will implement

2024-01-09 03:34 UTC, josefbaltz commented on src/main/java/tv/galaxe/genesis/cmd/ResetClass.java
> +		return true;
Implemented with [31843c7](https://github.com/GalaxeTV/Genesis/pull/28/commits/31843c72bf86666fa7e51c152680e7767c032bf7)

2024-01-09 03:36 UTC, josefbaltz commented on src/main/resources/plugin.yml
> +    aliases: [genreset, greset]
Deciding against this as it's not really necessary to restrict this command to people with a class. This is a useful troubleshooting step that could be used regardless if a class is selected or not.

2024-01-09 04:46 UTC, garrettsummerfi3ld approved these changes

2024-01-09 17:07 UTC, tonyswink approved these changes
LGTM.

2024-01-18 02:50 UTC, merged